version: '3.8'

services:
  enyata-db:
    container_name: enyata-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enyata-db
    ports:
      - '5432:5432'
    volumes:
      - enyata-db:/var/lib/postgresql/data

  enyata-adminer:
    container_name: enyata-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - enyata-db

volumes:
  enyata-db:
